#!/bin/sh

if [ -p /dev/stdin ]; then
  cat - | /usr/local/bin/docker run --env ALIASES_PWD="${ALIASES_PWD:-$PWD}" --interactive --network "host" --privileged --rm $(test "$(if tty >/dev/null; then echo true; else echo false; fi)" = "true" && echo "--tty") --volume "/usr/local/bin/docker:/usr/local/bin/docker" --volume "/var/run/docker.sock:/var/run/docker.sock" --volume "[TEMP_DIR]/kubectl:/usr/local/bin/kubectl" alpine:${ALPINE_VERSION:-"3.8"} "$@"
  exit $?
else
  /usr/local/bin/docker run --env ALIASES_PWD="${ALIASES_PWD:-$PWD}" --interactive --network "host" --privileged --rm $(test "$(if tty >/dev/null; then echo true; else echo false; fi)" = "true" && echo "--tty") --volume "/usr/local/bin/docker:/usr/local/bin/docker" --volume "/var/run/docker.sock:/var/run/docker.sock" --volume "[TEMP_DIR]/kubectl:/usr/local/bin/kubectl" alpine:${ALPINE_VERSION:-"3.8"} "$@"
  exit $?
fi