#!/bin/sh

if [ -p /dev/stdin ]; then
  cat - | /usr/local/bin/docker run --interactive --network "host" --rm --volume "[HOME]/.kube:/root/.kube" --volume "${ALIASES_PWD:-$PWD}:/kube" --workdir "/kube" chatwork/kubectl:${KUBECTL_VERSION:-"1.11.2"} "$@"
  exit $?
else
  /usr/local/bin/docker run --interactive --network "host" --rm --volume "[HOME]/.kube:/root/.kube" --volume "${ALIASES_PWD:-$PWD}:/kube" --workdir "/kube" chatwork/kubectl:${KUBECTL_VERSION:-"1.11.2"} "$@"
  exit $?
fi