#!/bin/sh

TEMPDIR="[ALIASE_TEMP_DIR]"
if [ -z "${ALIASES_PWD}" ]; then
  echo "" > ${TEMPDIR}/foo.env
  for line in $(env | grep "^FOO_"); do
    echo "${line#FOO_}" >> ${TEMPDIR}/foo.env
  done
fi
if [ -p /dev/stdin ]; then
  cat - | docker run --env-file "${TEMPDIR}/foo.env" --interactive --network "host" --rm $(tty >/dev/null && echo "--tty") alpine:${ALPINE1_VERSION:-"3.8"} "$@"
  exit $?
elif [ -f /dev/stdin ]; then
  docker run --env-file "${TEMPDIR}/foo.env" --interactive --network "host" --rm $(tty >/dev/null && echo "--tty") alpine:${ALPINE1_VERSION:-"3.8"} "$@" </dev/stdin
  exit $?
elif [ -t 0 ]; then
  docker run --env-file "${TEMPDIR}/foo.env" --interactive --network "host" --rm $(tty >/dev/null && echo "--tty") alpine:${ALPINE1_VERSION:-"3.8"} "$@"
  exit $?
else
  echo "" >/dev/null | docker run --env-file "${TEMPDIR}/foo.env" --interactive --network "host" --rm $(tty >/dev/null && echo "--tty") alpine:${ALPINE1_VERSION:-"3.8"} "$@"
  exit $?
fi