#!/bin/sh

if [ -p /dev/stdin ]; then
  cat - | /usr/local/bin/docker run --interactive --network "host" --rm alpine:${ALPINE_VERSION:-"3.8"} "$@"
  exit $?
else
  /usr/local/bin/docker run --interactive --network "host" --rm alpine:${ALPINE_VERSION:-"3.8"} "$@"
  exit $?
fi