#!/bin/sh

if [ -p /dev/stdin ]; then
  cat - | docker run --entrypoint "sh" --interactive --network "host" --rm $(tty >/dev/null && echo "--tty") alpine:${SH_VERSION:-"3.8"} -c "$@"
  exit $?
else
  echo "" >/dev/null | docker run --entrypoint "sh" --interactive --network "host" --rm $(tty >/dev/null && echo "--tty") alpine:${SH_VERSION:-"3.8"} -c "$@"
  exit $?
fi