#!/bin/sh

if [ -p /dev/stdin ]; then
  cat - | docker run --entrypoint "/483f2304b49063680c75e3c9e09cf6d0" --interactive --network "host" --rm $(tty >/dev/null && echo "--tty") --volume "[TEMP_DIR]/entrypoint/483f2304b49063680c75e3c9e09cf6d0:/483f2304b49063680c75e3c9e09cf6d0" alpine:${ALPINE_VERSION:-"3.8"} "$@"
  exit $?
elif [ -f /dev/stdin ]; then
  docker run --entrypoint "/483f2304b49063680c75e3c9e09cf6d0" --interactive --network "host" --rm $(tty >/dev/null && echo "--tty") --volume "[TEMP_DIR]/entrypoint/483f2304b49063680c75e3c9e09cf6d0:/483f2304b49063680c75e3c9e09cf6d0" alpine:${ALPINE_VERSION:-"3.8"} "$@" </dev/stdin
  exit $?
else
  echo "" >/dev/null | docker run --entrypoint "/483f2304b49063680c75e3c9e09cf6d0" --interactive --network "host" --rm $(tty >/dev/null && echo "--tty") --volume "[TEMP_DIR]/entrypoint/483f2304b49063680c75e3c9e09cf6d0:/483f2304b49063680c75e3c9e09cf6d0" alpine:${ALPINE_VERSION:-"3.8"} "$@"
  exit $?
fi