#!/bin/sh

if [ -p /dev/stdin ]; then
  cat - | docker run --interactive --network "host" --rm $(test "$(if tty >/dev/null; then echo true; else echo false; fi)" = "true" && echo "--tty") alpine:${ALPINE1_VERSION:-"3.8"} "$@"
  exit $?
else
  echo "" | docker run --interactive --network "host" --rm $(test "$(if tty >/dev/null; then echo true; else echo false; fi)" = "true" && echo "--tty") alpine:${ALPINE1_VERSION:-"3.8"} "$@"
  exit $?
fi