#!/bin/sh

if [ -p /dev/stdin ]; then
  cat - | docker run --env FOO="${FOO}" --env ALIASES_PWD="${ALIASES_PWD:-$PWD}" --interactive --network "host" --privileged --rm $(test "$(if tty >/dev/null; then echo true; else echo false; fi)" = "true" && echo "--tty") --volume "[HOME]/.aliases/docker/docker-18-09-0:/usr/local/bin/docker" --volume "/var/run/docker.sock:/var/run/docker.sock" --volume "[TEMP_DIR]/alpine1:/usr/local/bin/alpine1" --volume "[TEMP_DIR]/4d89908fa7d1581bb3aaa1558f57ce08/alpine3:/usr/local/bin/alpine3" alpine:${ALPINE2_VERSION:-"3.8"} "$@"
  exit $?
else
  echo "" | docker run --env FOO="${FOO}" --env ALIASES_PWD="${ALIASES_PWD:-$PWD}" --interactive --network "host" --privileged --rm $(test "$(if tty >/dev/null; then echo true; else echo false; fi)" = "true" && echo "--tty") --volume "[HOME]/.aliases/docker/docker-18-09-0:/usr/local/bin/docker" --volume "/var/run/docker.sock:/var/run/docker.sock" --volume "[TEMP_DIR]/alpine1:/usr/local/bin/alpine1" --volume "[TEMP_DIR]/4d89908fa7d1581bb3aaa1558f57ce08/alpine3:/usr/local/bin/alpine3" alpine:${ALPINE2_VERSION:-"3.8"} "$@"
  exit $?
fi